export default function PrivacyContentSection() {
  return (
    <section className="py-16 bg-white">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="prose prose-lg max-w-none">
          <div className="bg-emerald-50 border-l-4 border-emerald-600 p-6 mb-8">
            <p className="text-gray-700 leading-relaxed">
              KungfuBuy Company ("KungfuBuy", "we", "our") respects your privacy and is committed to taking reasonable steps to protect your online privacy and responsibly manage your information to best understand the products and services most useful to you. KungfuBuy provides dropshipping management software. This Privacy Policy is designed to inform you of our online privacy practices, the types and categories of information that may be collected, disclosed and stored, how the information is used, with whom the information may be shared, what choices you have regarding the collection, use and distribution of information, what security procedures are in place to prevent loss, misuse or alteration of information, and your rights regarding personal information and how to contact us to resolve issues or concerns.
            </p>
          </div>

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">By Using This Service You Agree</h2>
          <p className="text-gray-700 mb-6">
            By using the website, KungfuBuy software and/or contacting us and providing any personal information, you agree to our collection and use of information in accordance with this Privacy Policy and the Website Terms of Service. If we decide to change our privacy policy, we will post those changes on this page.
          </p>

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Definitions</h2>
          <div className="space-y-4 mb-6">
            <div>
              <strong className="text-gray-900">Service:</strong>
              <span className="text-gray-700"> Service refers to the kungfubuy.com website operated by KungfuBuy.</span>
            </div>
            <div>
              <strong className="text-gray-900">Personal Data:</strong>
              <span className="text-gray-700"> Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</span>
            </div>
            <div>
              <strong className="text-gray-900">Usage Data:</strong>
              <span className="text-gray-700"> Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</span>
            </div>
            <div>
              <strong className="text-gray-900">Cookies:</strong>
              <span className="text-gray-700"> Cookies are small pieces of data stored on your device (computer or mobile device).</span>
            </div>
            <div>
              <strong className="text-gray-900">Data Controller:</strong>
              <span className="text-gray-700"> Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed. For the purpose of this Privacy Policy, KungfuBuy is a Data Controller of your Personal Data.</span>
            </div>
          </div>

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Types of Data Collected</h2>
          
          <h3 className="text-xl font-semibold text-gray-900 mt-6 mb-3">Personal Data</h3>
          <p className="text-gray-700 mb-4">
            While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:
          </p>
          <ul className="list-disc list-inside text-gray-700 mb-6 space-y-2">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Cookies and Usage Data</li>
          </ul>

          <h3 className="text-xl font-semibold text-gray-900 mt-6 mb-3">Usage Data</h3>
          <p className="text-gray-700 mb-6">
            We may also collect information on how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
          </p>

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">How We Use Collected Information</h2>
          <p className="text-gray-700 mb-4">KungfuBuy uses the collected data for various purposes:</p>
          <ul className="list-disc list-inside text-gray-700 mb-6 space-y-2">
            <li>To provide and maintain our Service</li>
            <li>To notify you about changes to our Service</li>
            <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
            <li>To provide customer support</li>
            <li>To gather analysis or valuable information so that we can improve our Service</li>
            <li>To monitor the usage of our Service</li>
            <li>To detect, prevent and address technical issues</li>
            <li>To provide you with news, special offers and general information about other goods, services and events which we offer</li>
          </ul>

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Data Sharing and Use</h2>
          <p className="text-gray-700 mb-6">
            We will never share, sell or rent individual personal information with anyone for their promotional use without your prior permission or unless ordered by a court of law, subpoena, to protect our rights, or in the sale of our business. Information submitted to us is only available to employees managing this information for purposes of contacting you or sending you emails based on your request for information, and to contracted service providers and other third parties for purposes of providing services relating to our communications with you.
          </p>

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Data Retention</h2>
          <p className="text-gray-700 mb-6">
            KungfuBuy will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
          </p>

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Data Transfer</h2>
          <p className="text-gray-700 mb-6">
            Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction. If you are located outside China and choose to provide information to us, please note that we transfer the data, including Personal Data, to China and process it there. Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
          </p>

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Disclosure of Data</h2>
          <h3 className="text-xl font-semibold text-gray-900 mt-6 mb-3">Legal Requirements</h3>
          <p className="text-gray-700 mb-4">KungfuBuy may disclose your Personal Data in the good faith belief that such action is necessary to comply with a legal obligation or in response to valid requests by public authorities (e.g. a court or a government agency). KungfuBuy may disclose your Personal Data in good faith belief that such action is necessary to:</p>
          <ul className="list-disc list-inside text-gray-700 mb-6 space-y-2">
            <li>Comply with a legal obligation</li>
            <li>Protect and defend the rights or property of KungfuBuy</li>
            <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
            <li>Protect the personal safety of users of the Service or the public</li>
            <li>Protect against legal liability</li>
          </ul>

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Data Security</h2>
          <p className="text-gray-700 mb-6">
            The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
          </p>

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Your Rights</h2>
          <div className="space-y-4 mb-6">
            <div>
              <strong className="text-gray-900">Right to Deletion:</strong>
              <span className="text-gray-700"> You may have the right to request that we delete Personal Information that we collected from you. Certain information may be exempt from such requests under applicable law. We need certain types of information so that we can provide our services to you. If you ask us to delete it, you may no longer be able to access or use our services.</span>
            </div>
            <div>
              <strong className="text-gray-900">Right to Non-Discrimination:</strong>
              <span className="text-gray-700"> We will not deny, charge different prices for, or provide a different level of quality of goods or services if you choose to exercise these rights.</span>
            </div>
          </div>

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Children's Privacy</h2>
          <p className="text-gray-700 mb-6">
            Our Service does not address anyone under the age of 18 ("Children"). We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.
          </p>

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Contact Us</h2>
          <p className="text-gray-700 mb-4">
            If you have any questions about this Privacy Policy, or have any related requests, please contact us:
          </p>
          <div className="bg-gray-50 p-6 rounded-lg">
            <p className="text-gray-700">
              <strong>Email:</strong> business@kungfubuy.com
            </p>
            <p className="text-gray-700 mt-2">
              <strong>Phone:</strong> +86 130-5451-7917
            </p>
            <p className="text-gray-700 mt-2">
              <strong>Address:</strong> Building 1, Blue Intelligence Valley, High-tech Zone, Yantai City, Shandong Province, China
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
